# Generated by Django 3.2 on 2021-06-11 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='browser_title',
        ),
    ]
